# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BoostAttendance' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'FSCalendar' 
# Pods for BoostAttendance

end
